### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JSONovich/jsonovich#25]
```
Now that we have a lot more user-facing text, it would be prudent to find a way 
to translate it all easily.

Pretty much all of the existing examples are for the old way that doesn't work 
with restartless addons, could be interesting to see what the jetpack people 
come up with.
```

Original issue reported on code.google.com by `W.Elwoo...@gmail.com` on 1 Sep 2011 at 4:44

**Comment by welwood08** [comment]
Localisation is now [relatively easy in webext](https://developer.mozilla.org/Add-ons/WebExtensions/Internationalization), just needs contributions from people that know languages other than English well enough. If anyone's interested, feel free to send a PR.
