### ISSUE TITLE
dead links everywhere

### ISSUE THREAD

**Issue by romain-dartigues** [JSONovich/jsonovich#41]
Hi,

here is a list of dead links i stumbled uppon:
- https://addons.mozilla.org/en-US/firefox/addon/jsonovich/ "Developer's comments" links to code.google.com pages instead of GitHub
- about:addons JSONovich 1.9.7.1.1 page refers to http://mike.giarlo.name/blog/json-in-firefox/
- http://mike.giarlo.name/projects/ could also link to the project page

Regards.

**Comment by welwood08** [comment]
With the stable release of v2, the last of the dead links (homepage shown in addons manager) should be gone. Thanks for reporting, please do let me know if I've missed any.
