### ISSUE TITLE
WebExtension rewrite

### ISSUE THREAD

**Issue by welwood08** [JSONovich/jsonovich#43]
Hi there, I thought I'd signal my interest in returning to addon development after a long hiatus by looking into the feasibility of JSONovich continuing to exist in Firefox 57 and beyond - I assume I'm not duplicating anybody else's efforts. I've conducted preliminary experiments to see what of the current feature-set would be possible to achieve in a WebExtensions world and the results have been promising.

Features that could be ported:
- [x] Inserting JSON MIME type into outgoing `Accept` header (both by default and only for specific domains).
- [x] Treating user-configurable MIME types and file extensions as JSON.
- [x] Overriding Firefox's built-in JSON viewer with our own.

If I've left any major component off that list, please let me know so I can investigate.

So far I've encountered a [couple](https://bugzilla.mozilla.org/show_bug.cgi?id=1376045) of [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1376060) with overriding Firefox's built-in viewer, but in the worst case we can just use that since it's currently more feature-ful and better with big files than what I wrote by myself all those years ago.

Given that there doesn't seem to be any major blocker to continued existence, I propose to migrate existing user preferences by way of a transitional hybrid addon that copies settings into WebExtension-accessible storage ASAP followed in the next few months by an actual WebExtension implementation.

@mjgiarlo Do you have any objection to this plan? Would you prefer pull requests or just to add me as a committer to this repo? (Thanks for exporting it from Gcode btw!)

**Comment by mjgiarlo** [comment]
Hey, @welwood08! I invited you as a collaborator. Let me know if that doesn't do the trick.

:shipit:

**Comment by welwood08** [comment]
Thanks for collaborator access, it does indeed do the trick!

The 1st phase, preferences migration, is now live on AMO. I'll leave it there for at least a month regardless of progress on the rest of the implementation to ensure most users get migrated.

**Comment by welwood08** [comment]
Most of the hard work is done now! :triumph:

There were a couple of critical bugs that meant I couldn't leave phase 1 on AMO like I planned:
- The preferences migration was [totally broken](https://github.com/mjgiarlo/jsonovich/commit/b86d1ee072eac6ab3510e307b481c5cfd7443fae#diff-80a786ec81134b99a212082a2d6a6cf2)! Not sure how that slipped through my testing, I think I was experimenting with how the defaults object was structured or something.
- Most core functionality stopped working some time after Firefox 52 (ESR). At least the ability to override the now default-enabled built-in JSON viewer and register the actual stream converter had broken with no obvious fix.

I've worked around the [1st](https://bugzilla.mozilla.org/show_bug.cgi?id=1376045) of the 2 platform bugs mentioned at the top, temporarily mitigated the [2nd](https://bugzilla.mozilla.org/show_bug.cgi?id=1376060) (will become an issue again as soon as the legacy addon is removed), wasted several hours before realising I was hitting [another](https://bugzilla.mozilla.org/show_bug.cgi?id=1372750) and had to use [an ugly hack to inject CSS](https://github.com/mjgiarlo/jsonovich/commit/b86d1ee072eac6ab3510e307b481c5cfd7443fae#diff-eb6bea392670679666b995cd6b0f84d8) (not sure if it's a bug or I'm just misunderstanding docs). Only remaining issue I'm aware of is a flash of unstyled content, which probably can't be fixed unless platform decides to allow reliable `executeScript`/`insertCSS` earlier in the load.

Revised plan:
- Keep the legacy preferences migration in place for at least a month after a working version passes AMO review.
- Phase 3: implement a webext options UI and remove legacy options UI. This will no longer include preferences migration but will still mitigate [bug 1376060](https://bugzilla.mozilla.org/show_bug.cgi?id=1376060).
- Phase 4: extract the embedded webextension and throw away the legacy wrapper. Aim for Firefox 57 beta at the end of September for testing but delay main AMO release until November if [bug 1376060](https://bugzilla.mozilla.org/show_bug.cgi?id=1376060) still isn't fixed to minimise fallout.

**Comment by welwood08** [comment]
In case anyone is following progress here, I've just uploaded the first v2 beta to [AMO](https://addons.mozilla.org/firefox/addon/jsonovich/#beta-channel).

Feedback on the options UI would be most welcome - I've been slowly progressing it to this stage in a vacuum but I felt it was time to open it up. Particularly interested in any ideas for how to let a user edit the Accept header override to use a different MIME type and/or q-value (implementation is already capable).

**Comment by welwood08** [comment]
v2 has now been approved on AMO.
