### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by welwood08** [JSONovich/jsonovich#46]
I'm considering switching the license to [MPL 2](https://www.mozilla.org/MPL/2.0/) to get rid of the old messy tri-licensing and this upcoming major release seems like a good opportunity. @mjgiarlo Any objections? I'm not sure how much of your code, if any, remains anymore.

**Comment by mjgiarlo** [comment]
@welwood08 Please do! I hereby consent to this change. Thank you for all of your work on this, and keeping me in the loop. :)
