### ISSUE TITLE
GitHub organization?

### ISSUE THREAD

**Issue by welwood08** [JSONovich/jsonovich#47]
@mjgiarlo I've discovered a couple of things my collaborator access doesn't allow me to do, such as edit the `Automatically exported from code.google.com/p/jsonovich` description or create webhooks.

Since it doesn't seem right for me to disturb you every time I find something like that, would you be willing to transfer this repo to a new `jsonovich` organization so we can share owner permissions?

**Comment by mjgiarlo** [comment]
@welwood08 absolutely.

**Comment by welwood08** [comment]
@mjgiarlo Thanks for the quick setup! Looks like I'll be able to do the things I mentioned above now.

**Comment by mjgiarlo** [comment]
@welwood08 Great! Glad to hear it. See also #48.
