### ISSUE TITLE
Not working inside a frameset

### ISSUE THREAD

**Issue by LarryGT** [JSONovich/jsonovich#51]
Hi,
the addon does not work when i use a frameset. When the url is opened in an extra tab everything is ok.
I have a simple frameset with one frame containing a list of test-urls and one frame to display the response. In this case the addon does not work. The code is just displayed as text normally by Firefox

**Comment by welwood08** [comment]
Pushed new version before remembering this was another easy fix. /o\

**Comment by LarryGT** [comment]
Hi, i tested version 2.0.2 and it is still not working with a frameset

**Comment by welwood08** [comment]
Would you be able to provide a test case? I assumed the solution was obvious since I was previously only formatting main frames and not subframes, but I didn't actually test it.

**Comment by LarryGT** [comment]
Hi,
i attached a simple example.

[FrameTest.zip](https://github.com/JSONovich/jsonovich/files/1743627/FrameTest.zip)

**Comment by welwood08** [comment]
This fix is available in version 2.1.2 now, thanks again.

**Comment by LarryGT** [comment]
Thanks
